version: '3'
services:
  ftp:
    image: fauria/vsftpd
    volumes:
      - ./ftp:/srv/ftp
    ports:
      - "20:20"
      - "21:21"
    environment:
      FTP_USER: “paurique”
      FTP_PASS: “reyney15”
      FTP_ADDRESS: “localhost”